### Divvy_Exercise_Full_Year_Analysis ###

# This analysis is based on the Divvy case study "'Sophisticated, Clear, and Polished’: Divvy and Data Visualization" written by Kevin Hartman (found here: https://artscience.blog/home/divvy-dataviz-case-study). The purpose of this script is to consolidate downloaded Divvy data into a single dataframe and then conduct simple analysis to help answer the key question: “In what ways do members and casual riders use Divvy bikes differently?”

# # # # # # # # # # # # # # # # # # # # # # # 
# Install required packages
# tidyverse for data import and wrangling
# lubridate for date functions
# ggplot for visualization
# # # # # # # # # # # # # # # # # # # # # # #  

install.packages("tidyverse")
install.packages("lubridate")
install.packages("ggplot2")
install.packages("dplyr")
install.packages("plyr") 

# Libraries loaded
library(tidyverse)
library(lubridate)
library(ggplot2)
library(dplyr)
library(plyr) 

# Set working directory (for uploading dataset)

setwd("C:/Users/oguzo/OneDrive/Belgeler/R_dataset/Datasets")

#=====================
# STEP 1: COLLECT DATA
#=====================

# Read csv files in working directory

d_202201 <- read_csv("202201-divvy-tripdata.csv")
d_202202 <- read_csv("202202-divvy-tripdata.csv")
d_202203 <- read_csv("202203-divvy-tripdata.csv")
d_202204 <- read_csv("202204-divvy-tripdata.csv")
d_202205 <- read_csv("202205-divvy-tripdata.csv")
d_202206 <- read_csv("202206-divvy-tripdata.csv")
d_202207 <- read_csv("202207-divvy-tripdata.csv")
d_202208 <- read_csv("202208-divvy-tripdata.csv")
d_202209 <- read_csv("202209-divvy-tripdata.csv")
d_202210 <- read_csv("202210-divvy-tripdata.csv")
d_202211 <- read_csv("202211-divvy-tripdata.csv")
d_202212 <- read_csv("202212-divvy-tripdata.csv")

#====================================================
# STEP 2: WRANGLE DATA AND COMBINE INTO A SINGLE FILE
#====================================================

# Compared column names each of the files while the names don't have to be in the same order, they DO need to match perfectly before we can use a command to join them into one file

colnames(d_202203)
colnames(d_202207)
colnames(d_202212)

# Renamed columns to make them consistent with tables (as this will be the supposed going-forward table design for Divvy)

(d_202201 <- plyr::rename(d_202201,c(
                   ride_id = "trip_id",
                   rideable_type = "bikeid",
                   started_at = "start_time", 
                   ended_at = "end_time",  
                   start_station_name = "from_station_name",
                   start_station_id = "from_station_id",
                   end_station_name = "to_station_name",
                   end_station_id = "to_station_id",
                   member_casual = "usertype")))

(d_202202 <- plyr::rename(d_202202,c(
                   ride_id = "trip_id",
                   rideable_type = "bikeid",
                   started_at = "start_time", 
                   ended_at = "end_time",  
                   start_station_name = "from_station_name",
                   start_station_id = "from_station_id",
                   end_station_name = "to_station_name",
                   end_station_id = "to_station_id",
                   member_casual = "usertype")))

(d_202203 <- plyr::rename(d_202203,c(
                   ride_id = "trip_id",
                   rideable_type = "bikeid",
                   started_at = "start_time", 
                   ended_at = "end_time",  
                   start_station_name = "from_station_name",
                   start_station_id = "from_station_id",
                   end_station_name = "to_station_name",
                   end_station_id = "to_station_id",
                   member_casual = "usertype")))
                   
(d_202204 <- plyr::rename(d_202204,c(
                   ride_id = "trip_id",
                   rideable_type = "bikeid",
                   started_at = "start_time", 
                   ended_at = "end_time",  
                   start_station_name = "from_station_name",
                   start_station_id = "from_station_id",
                   end_station_name = "to_station_name",
                   end_station_id = "to_station_id",
                   member_casual = "usertype")))

(d_202205 <- plyr::rename(d_202205,c(
                   ride_id = "trip_id",
                   rideable_type = "bikeid",
                   started_at = "start_time", 
                   ended_at = "end_time",  
                   start_station_name = "from_station_name",
                   start_station_id = "from_station_id",
                   end_station_name = "to_station_name",
                   end_station_id = "to_station_id",
                   member_casual = "usertype")))

(d_202206 <- plyr::rename(d_202206,c(
                   ride_id = "trip_id",
                   rideable_type = "bikeid",
                   started_at = "start_time", 
                   ended_at = "end_time",  
                   start_station_name = "from_station_name",
                   start_station_id = "from_station_id",
                   end_station_name = "to_station_name",
                   end_station_id = "to_station_id",
                   member_casual = "usertype")))

(d_202207 <- plyr::rename(d_202207,c(
                   ride_id = "trip_id",
                   rideable_type = "bikeid",
                   started_at = "start_time", 
                   ended_at = "end_time",  
                   start_station_name = "from_station_name",
                   start_station_id = "from_station_id",
                   end_station_name = "to_station_name",
                   end_station_id = "to_station_id",
                   member_casual = "usertype")))
                   
(d_202208 <- plyr::rename(d_202208,c(
                   ride_id = "trip_id",
                   rideable_type = "bikeid",
                   started_at = "start_time", 
                   ended_at = "end_time",  
                   start_station_name = "from_station_name",
                   start_station_id = "from_station_id",
                   end_station_name = "to_station_name",
                   end_station_id = "to_station_id",
                   member_casual = "usertype")))
                   
                   
(d_202209 <- plyr::rename(d_202209,c(
                   ride_id = "trip_id",
                   rideable_type = "bikeid",
                   started_at = "start_time", 
                   ended_at = "end_time",  
                   start_station_name = "from_station_name",
                   start_station_id = "from_station_id",
                   end_station_name = "to_station_name",
                   end_station_id = "to_station_id",
                   member_casual = "usertype")))

(d_202210 <- plyr::rename(d_202210,c(
                   ride_id = "trip_id",
                   rideable_type = "bikeid",
                   started_at = "start_time", 
                   ended_at = "end_time",  
                   start_station_name = "from_station_name",
                   start_station_id = "from_station_id",
                   end_station_name = "to_station_name",
                   end_station_id = "to_station_id",
                   member_casual = "usertype")))

(d_202211 <- plyr::rename(d_202211,c(
                   ride_id = "trip_id",
                   rideable_type = "bikeid",
                   started_at = "start_time", 
                   ended_at = "end_time",  
                   start_station_name = "from_station_name",
                   start_station_id = "from_station_id",
                   end_station_name = "to_station_name",
                   end_station_id = "to_station_id",
                   member_casual = "usertype")))
                   
(d_202212 <- plyr::rename(d_202212,c(
                   ride_id = "trip_id",
                   rideable_type = "bikeid",
                   started_at = "start_time", 
                   ended_at = "end_time",  
                   start_station_name = "from_station_name",
                   start_station_id = "from_station_id",
                   end_station_name = "to_station_name",
                   end_station_id = "to_station_id",
                   member_casual = "usertype")))
                   
# Inspect the dataframes and look for incongruencies
str(d_202201)
str(d_202205)
str(d_202209)
str(d_202212)

# Converted ride_id and rideable_type to character so that they can stack correctly

d_202201 <-  mutate(d_202201, trip_id = as.character(trip_id),
bikeid = as.character(bikeid))

d_202202 <-  mutate(d_202202, trip_id = as.character(trip_id),
bikeid = as.character(bikeid))

d_202203 <-  mutate(d_202203, trip_id = as.character(trip_id),
bikeid = as.character(bikeid))

d_202204 <-  mutate(d_202204, trip_id = as.character(trip_id),
bikeid = as.character(bikeid))

d_202205 <-  mutate(d_202205, trip_id = as.character(trip_id),
bikeid = as.character(bikeid))

d_202206 <-  mutate(d_202206, trip_id = as.character(trip_id),
bikeid = as.character(bikeid))

d_202207 <-  mutate(d_202207, trip_id = as.character(trip_id),
bikeid = as.character(bikeid))

d_202208 <-  mutate(d_202208, trip_id = as.character(trip_id),
bikeid = as.character(bikeid))

d_202209 <-  mutate(d_202209, trip_id = as.character(trip_id),
bikeid = as.character(bikeid))

d_202210 <-  mutate(d_202210, trip_id = as.character(trip_id),
bikeid = as.character(bikeid))

d_202211 <-  mutate(d_202211, trip_id = as.character(trip_id),
bikeid = as.character(bikeid))

d_202212 <-  mutate(d_202212, trip_id = as.character(trip_id),
bikeid = as.character(bikeid))

# Stacked month data frames into one big data frame
all_trips <- bind_rows(d_202201, d_202202, d_202203, d_202204, d_202205, d_202206, d_202207, d_202208, d_202209, d_202210, d_202211, d_202212)

glimpse(all_trips)

# Removed lat and long fields as this data was dropped beginning in 2022

all_trips <- all_trips %>%  
  select(-c(start_lat, start_lng, end_lat, end_lng))

glimpse(all_trips)

#======================================================
# STEP 3: CLEAN UP AND ADD DATA TO PREPARE FOR ANALYSIS
#======================================================

# Inspect the new table that has been created
colnames(all_trips)
# How many rows are in data frame?
nrow(all_trips)
# Dimensions of the data frame?
dim(all_trips)
# See the first 6 rows of data frame.
head(all_trips)
# See list of columns and data types (numeric, character, etc)
str(all_trips) 
# Statistical summary of data. Mainly for numerics
summary(all_trips) 

# There are a few problems that manager warned me to fix:

# (1) In the "member_casual" column, there are two names for members ("member" and "Subscriber") and two names for casual riders ("Customer" and "casual"). We will need to consolidate that from four to two labels.

print(tail(select(all_trips, usertype), n = 20), n = 20)
unique(select(all_trips, usertype))
table(all_trips$usertype)

# I checked that there are 2 types which are casual and member. Data looks ok

# (2) The data can only be aggregated at the ride-level, which is too granular. We will want to add some additional columns of data -- such as day, month, year -- that provide additional opportunities to aggregate the data.

# The default format is yyyy-mm-dd

all_trips$date <- as.Date(all_trips$start_time)
all_trips$month <- format(as.Date(all_trips$date), "%m")
all_trips$day <- format(as.Date(all_trips$date), "%d")
all_trips$year <- format(as.Date(all_trips$date), "%Y")
all_trips$day_of_week <- format(as.Date(all_trips$date), "%A")

# (3) We will want to add a calculated field for length of ride since dataframes did not have the "tripduration" column. We will add "ride_length" to the entire dataframes for consistency.

all_trips$ride_length <- difftime(all_trips$end_time,all_trips$start_time)

table(all_trips$ride_length)

# Ride length in seconds and it containes minus (-) values. Noted and code ok.

# (4) There are some rides where tripduration shows up as negative, including several hundred rides where Divvy took bikes out of circulation for Quality Control reasons. We want you to delete these rides.

# Converted "ride_length" from Factor to numeric so I can run calculations on the data

is.factor(all_trips$ride_length)
all_trips$ride_length <- as.numeric(as.character(all_trips$ride_length))

is.numeric(all_trips$ride_length)

# Removing "bad" data, the dataframe includes a few hundred entries when bikes were taken out of docks and checked for quality by Divvy or ride_length was negative. I will create a new version of the dataframe (v2) since data is being removed

all_trips_cleaned <- all_trips[!(all_trips$from_station_name == "HQ QR" | all_trips$ride_length<0),]

all_trips_cleaned <- all_trips_cleaned %>% drop_na()

#=====================================
# STEP 4: CONDUCT DESCRIPTIVE ANALYSIS
#=====================================

# Descriptive analysis on ride_length (all figures in seconds)

# straight average (total ride length / rides)
mean(all_trips_cleaned$ride_length)
# midpoint number in the ascending array of ride lengths
median(all_trips_cleaned$ride_length)
# longest ride
max(all_trips_cleaned$ride_length) 
# shortest ride
min(all_trips_cleaned$ride_length) 

# I can condense the four lines above to one line using summary() on the specific attribute
summary(all_trips_cleaned$ride_length)

# Compare members and casual users
aggregate(all_trips_cleaned$ride_length ~ all_trips_cleaned$usertype, FUN = mean)
aggregate(all_trips_cleaned$ride_length ~ all_trips_cleaned$usertype, FUN = median)
aggregate(all_trips_cleaned$ride_length ~ all_trips_cleaned$usertype, FUN = max)
aggregate(all_trips_cleaned$ride_length ~ all_trips_cleaned$usertype, FUN = min)

# See the average ride time by each day for members vs casual users
aggregate(all_trips_cleaned$ride_length ~ all_trips_cleaned$usertype + all_trips_cleaned$day_of_week, FUN = mean)

# Notice that the days of the week are out of order. Let's fix that.
all_trips_cleaned$day_of_week <- ordered(all_trips_cleaned$day_of_week, levels=c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"))

# Now, let's run the average ride time by each day for members vs casual users
aggregate(all_trips_cleaned$ride_length ~ all_trips_cleaned$usertype + all_trips_cleaned$day_of_week, FUN = mean)

# Analyzed ridership data by type and weekday

#creates weekday field using wday(), groups by usertype and weekday, #calculates the number of rides and average duration, calculates the average duration 

all_trips_cleaned %>% 
  mutate(weekday = wday(start_time, label = TRUE)) %>% 
  group_by(usertype, weekday) %>%
  dplyr::summarise(number_of_rides = n(),						
  average_duration = mean(ride_length)) %>% 		
  arrange(usertype, weekday)	

# Let's visualize the number of rides by rider type
all_trips_cleaned %>% 
  mutate(weekday = wday(start_time, label = TRUE)) %>% 
  group_by(usertype, weekday) %>%
  dplyr::summarise(number_of_rides = n(),
  average_duration = mean(ride_length)) %>% 		
  arrange(usertype, weekday) %>% 
  ggplot(aes(x = weekday, y = number_of_rides, fill = usertype)) +
  geom_col(position = "dodge")


# Let's create a visualization for average duration(in seconds)


all_trips_cleaned %>% 
  mutate(weekday = wday(start_time, label = TRUE)) %>% 
  group_by(usertype, weekday) %>%
  dplyr::summarise(number_of_rides = n(),
  average_duration = mean(ride_length)) %>% 		
  arrange(usertype, weekday) %>% 
  ggplot(aes(x = weekday, y = average_duration, fill = usertype)) +
  geom_col(position = "dodge")
  

#=================================================
# STEP 5: EXPORT SUMMARY FILE FOR FURTHER ANALYSIS
#=================================================

# Create a csv file that we will visualize in Excel, Tableau, or my presentation software


C_1 <- aggregate(all_trips_cleaned$ride_length ~ all_trips_cleaned$usertype + all_trips_cleaned$day_of_week, FUN = function(x) c(mean = mean(x), max = max(x)))

write.csv(C_1, file = "C:/Users/oguzo/OneDrive/Masaüstü/R_project/counts.csv")


